USE [master]
GO
/****** Object:  Database [Ramand]    Script Date: 10/03/1400 01:39:46 ب.ظ ******/
CREATE DATABASE [Ramand]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Ramand', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Ramand.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Ramand_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Ramand_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [Ramand] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Ramand].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Ramand] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Ramand] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Ramand] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Ramand] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Ramand] SET ARITHABORT OFF 
GO
ALTER DATABASE [Ramand] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Ramand] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Ramand] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Ramand] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Ramand] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Ramand] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Ramand] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Ramand] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Ramand] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Ramand] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Ramand] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Ramand] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Ramand] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Ramand] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Ramand] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Ramand] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Ramand] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Ramand] SET RECOVERY FULL 
GO
ALTER DATABASE [Ramand] SET  MULTI_USER 
GO
ALTER DATABASE [Ramand] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Ramand] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Ramand] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Ramand] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [Ramand] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Ramand', N'ON'
GO
USE [Ramand]
GO
/****** Object:  Table [dbo].[User]    Script Date: 10/03/1400 01:39:47 ب.ظ ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[ID] [uniqueidentifier] NOT NULL,
	[Username] [nvarchar](30) NOT NULL,
	[Password] [nvarchar](30) NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
INSERT [dbo].[User] ([ID], [Username], [Password]) VALUES (N'3ae9bf28-84d3-4cd4-b2be-1e7d0a4efc9c', N'PF8.ir', N'8888')
INSERT [dbo].[User] ([ID], [Username], [Password]) VALUES (N'3ae9bf28-84d3-4cd4-b2be-1e7d0a4efc8c', N'admin', N'admin')
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_User]    Script Date: 10/03/1400 01:39:47 ب.ظ ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_User] ON [dbo].[User]
(
	[Username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Ramand] SET  READ_WRITE 
GO
